api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    show_webby: false
    title: 'API Lebackoffice by ecowan'
    description: "API destinée aux utilisateurs interne et aux clients. Afin de pouvoir l'utiliser, vous devez utliser votre token d'api qui se trouve sur votre compte. Le token doit etre envoyé dans un header : `Authorization: Bearer {token}` pour toutes les requettes à l'API."
    version: '0.0.1'
    openapi:
        contact:
            name: 'BOYER Thomas'
            email: 'tboyer@ecowan.fr'