api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    show_webby: false
    title: 'API Lebackoffice by ecowan'
    description: "API for internal users and customers. To consume the api, you must generate a JWT token via `/api/login` and use it in your requests in the header : `Authorization: Bearer {JWT-token}`."
    version: '1.0.0'