knpu_oauth2_client:
    clients:
        discord:
            type: discord
            client_id: '%env(DISCORD_ID)%'
            client_secret: '%env(DISCORD_SECRET)%'
            redirect_route: oauth.check
            redirect_params:
                service: discord
        google:
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            redirect_route: oauth.check
            redirect_params:
                service: google
        github:
            type: github
            client_id: '%env(GITHUB_ID)%'
            client_secret: '%env(GITHUB_SECRET)%'
            redirect_route: oauth.check
            redirect_params:
              service: github
        microsoft:
            type: microsoft
            client_id: '%env(MICROSOFT_ID)%'
            client_secret: '%env(MICROSOFT_SECRET)%'
            redirect_route: oauth.check
            redirect_params:
              service: microsoft