scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true
        parameters:
            digits: 6
            digest: sha1
            period: 30
        issuer: Lebackoffice by ecowan
        template: security/2fa_form.html.twig
    email:
        enabled: true
        digits: 6
        sender_email: '%env(MAILER_FROM_EMAIL)%'
        sender_name: '%env(MAILER_FROM_NAME)%'
        template: security/2fa_form.html.twig
    trusted_device:
        enabled: true
        lifetime: 2592000
        extend_lifetime: false
        cookie_name: trusted_device
        cookie_secure: true
        cookie_same_site: "lax"
        cookie_path: "/"
    backup_codes:
        enabled: true