twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'tailwind_2_layout.html.twig'
    globals:
        configuration: "@App\\Repository\\ConfigRepository"

when@test:
    twig:
        strict_variables: true
