version: '3.8'
services:
    database:
        image: 'mariadb:latest'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lebackoffice
        ports:
            - "3306:3306"
    mailer:
        image: schickling/mailcatcher
        ports: [ 1025, 1080 ]
